export enum ConfigKey {
  NODE_ENV = 'NODE_ENV',
  FRONTEND_HOST = 'FRONTEND_HOST',
  PORT = 'PORT',
  ENABLE_SWAGGER = 'ENABLE_SWAGGER',

  POSTGRES_TIMEZONE = 'POSTGRES_TIMEZONE',
  POSTGRES_DB_NAME = 'POSTGRES_DB_NAME',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_DEBUG_MODE = 'POSTGRES_DEBUG_MODE',

  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',

  MAIL_HOST = 'MAIL_HOST',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',
  MAILDEV_WEB_PORT = 'MAILDEV_WEB_PORT',
}
