version: '3'

services:
  postgres:
    image: postgres:17.5-bullseye
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      TZ: '${POSTGRES_TIMEZONE}'

  maildev:
    image: maildev/maildev:2.2.1
    restart: always
    ports:
      - '${MAILDEV_WEB_PORT}:1080' # Web interface
      - '${MAIL_PORT}:1025' # SMTP server
    environment:
      - MAILDEV_WEB_PORT=${MAILDEV_WEB_PORT}
      - MAILDEV_SMTP_PORT=${MAIL_PORT}

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    restart: always
